"""Generate a per-city camdl model + IF2 scout-fit config for each of the
four Fig 1.4 cities.

The model is the He, Ionides & King (2010) seasonally forced stochastic
SEIR from ../camdl_replication/he2010_london.camdl (validated there against
pomp), re-pointed at each city's cases/covariates and its own observation
cadence.  Run:  uv run python make_city_models.py
"""

from pathlib import Path

import pandas as pd

HERE = Path(__file__).parent

MODEL_TEMPLATE = """\
# Seasonally forced stochastic SEIR (He, Ionides & King 2010 structure)
# for {label} measles — generated by make_city_models.py; do not hand-edit.
#
# Structure identical to camdl_replication/he2010_london.camdl (validated
# against pomp there): term-time forcing, cohort school-entry pulse,
# (I + iota)^alpha inhomogeneous mixing, Gamma noise on the FOI, and the
# He et al. discretized-Normal observation model on accumulated recoveries.

time_unit = 'days

compartments {{ S, E, I, R }}

parameters {{
  R0        : positive    in [1.0, 100.0]
  sigma     : rate        in [0.01, 0.5]
  gamma     : rate        in [0.01, 0.5]
  mu        : rate        in [1e-6, 0.01]
  alpha     : positive [1] in [0.5, 1.0]
  iota      : count       in [0.01, 100.0]
  sigma_se  : positive [1] in [0.001, 5.0]
  amplitude : probability in [0.0001, 0.9999]
  cohort    : probability in [0.0001, 0.9999]
  rho       : probability in [0.0001, 0.9999]
  psi       : positive [1] in [0.001, 1.0]
  s0        : probability in [0.001, 0.5]
  e0        : probability in [1e-6, 0.01]
  i0        : probability in [1e-6, 0.01]
  N0        : count       in [1000, 10000000]
}}

forcing {{
  pop : interpolated 'count {{
    data      = "data/{city}_covariates.tsv"
    time_col  = "t"
    value_col = "pop"
    method    = linear
  }}

  birthrate : interpolated 'per_year {{
    data      = "data/{city}_covariates.tsv"
    time_col  = "t"
    value_col = "birthrate"
    method    = linear
  }}

  # School-term forcing (term days 7-100, 115-199, 252-300, 308-356;
  # 277 school days / 365).  UK calendar, retained for the US cities as
  # an approximation — Dalziel et al. (2016) estimated US seasonal
  # transmission to track school terms closely.
  school : periodic 'ratio {{
    period = 365.25 'days
    step   = 1 'days
    on     = [7:100, 115:199, 252:300, 308:356]
  }}
}}

let beta_base = R0 * (1.0 - exp(-(gamma + mu) * 1 'days))
let seas = 1.0 - amplitude + amplitude * (1.0 + 0.2411 / 0.7589) * school(t)
let daily_births = birthrate(t) * pop(t)

transitions {{
  infection : S --> E  @ overdispersed(beta_base * seas * S * unchecked_dim((I + iota) ^ alpha, dim = population, reason = "He et al. alpha-mixing: phenomenological P^alpha term") / pop(t), sigma_se)
  latency   : E --> I  @ sigma * E
  recovery  : I --> R  @ gamma * I
  birth : --> S  @ deterministic((1.0 - cohort) * daily_births)
  death_S : S -->  @ mu * S
  death_E : E -->  @ mu * E
  death_I : I -->  @ mu * I
  death_R : R -->  @ mu * R
}}

init {{
  S = s0 * N0
  E = e0 * N0
  I = i0 * N0
  R = N0 - s0 * N0 - e0 * N0 - i0 * N0
}}

events {{
  cohort_entry : add(S, cohort * birthrate(t) * pop(t) * 1 'years)
    every 365.25 'days at_day 258
}}

balance {{
  R = pop(t) - S - E - I
}}

observations {{
  {obs_col} {{
    columns       {{ time : time, {obs_col} : count }}
    projected     = incidence(recovery)
    emit_schedule = every {emit_days} 'days
    {obs_col}  ~ normal(
      mean = rho * projected,
      sd   = sqrt(rho * projected * (1.0 - rho + psi * psi * rho * projected))
    )
  }}
}}

simulate {{
  from = 0 'days
  to   = {horizon} 'days
}}
"""

FIT_TEMPLATE = """\
# IF2 scout fit for {label} measles ({cadence} cases).
# Estimates the headline transmission parameters (R0, amplitude, rho, s0)
# while holding natural history and noise at He et al. (2010) London MLE
# values — a scout pass, not a full search.

output_dir = "results"

[model]
camdl = "{city}_seir.camdl"

[data.observations]
{obs_col} = "data/{city}_cases.tsv"

[estimate]
R0        = {{ bounds = [15.0, 80.0], start = 30.0 }}
amplitude = {{ bounds = [0.05, 0.9],  start = 0.3 }}
rho       = {{ bounds = [{rho_lo}, 0.95],  start = {rho_start} }}
s0        = {{ bounds = [0.01, 0.12], start = 0.04 }}
{sigma_se_line}
[fixed]
sigma    = 0.0791
gamma    = 0.0832
mu       = 0.0000548
alpha    = 0.976
iota     = 2.9
{sigma_se_fixed}cohort   = 0.557
psi      = 0.116
e0       = 0.0000517
i0       = 0.0000514
N0       = {n0}

[stages.scout]
algorithm  = "if2"
backend    = "chain_binomial"
chains     = 4
particles  = {particles}
iterations = 25
cooling    = 0.7

[config]
dt = 1.0
"""

# The UK fits hold sigma_se (extra-demographic noise) at He et al.'s London
# MLE; for the US cities that value is indefensible a priori and the first
# fit round bore that out (NY: PF degeneracy watchdog killed all chains;
# Baltimore: rho pinned at its bound), so the US fits estimate sigma_se and
# NY gets more particles — both fixes named by camdl's own diagnostics.
UK = dict(obs_col="weekly_cases", emit_days=7, cadence="weekly",
          rho_lo=0.2, rho_start=0.4, particles=2000,
          sigma_se_line="", sigma_se_fixed="sigma_se = 2.816\n")
US = dict(obs_col="biweekly_cases", emit_days=14, cadence="biweekly",
          rho_lo=0.05, particles=4000,
          sigma_se_line="sigma_se  = {{ bounds = [0.2, 5.0],  start = 1.5 }}\n".replace("{{", "{").replace("}}", "}"),
          sigma_se_fixed="")

CITIES = {
    "london": dict(label="London", **UK),
    "liverpool": dict(label="Liverpool", **UK),
    "newyork": dict(label="New York", rho_start=0.2, **US),
    "baltimore": dict(label="Baltimore", rho_start=0.3, **US),
}


def main():
    meta = pd.read_csv(HERE / "data" / "city_meta.tsv", sep="\t").set_index("city")
    for city, cfg in CITIES.items():
        cases = pd.read_csv(HERE / "data" / f"{city}_cases.tsv", sep="\t")
        horizon = int(cases["time"].max())
        n0 = int(round(meta.loc[city, "N0"]))
        model = MODEL_TEMPLATE.format(city=city, horizon=horizon, **cfg)
        (HERE / f"{city}_seir.camdl").write_text(model)
        fit = FIT_TEMPLATE.format(city=city, n0=n0, **cfg)
        (HERE / f"fit_{city}.toml").write_text(fit)
        print(f"{city}: horizon={horizon}d  N0={n0:,}  obs={len(cases)}")


if __name__ == "__main__":
    main()
