"""Generate per-country fit.toml configs for the SIR and SIRx models.

One config per (country, model). Priors are uniform over the ranges in
the paper's estimation scripts (sirx_model_estimations.py /
sir_model_estimations.py), which differ from the supplement's Table S2
in places (phi in [-135, -45] days; c in [0, 0.01]; kappa in [100, 5000]).
Stages: an NLopt Sbplx multi-start MLE scout, then adaptive
Metropolis-Hastings on the deterministic-ODE likelihood, warm-started
from the scout — the likelihood-based analogue of the paper's ABC-SMC.

The fit reads the *_train.tsv files (first wave only, up to the paper's
per-country cutoff from Table S1); the remaining days are the
out-of-sample prediction window, evaluated separately in analyze.py.
(camdl parses [data].holdout_after but does not yet apply it, so the
split is materialised in the data files.)
"""

from pathlib import Path

from prep_data import COUNTRIES

FIT_DIR = Path(__file__).parent / "fits"

SHARED_ESTIMATES = """\
beta    = {{ bounds = [0.1, 0.9],    start = 0.4,   transform = "identity", prior = {{ uniform = {{}} }} }}
b       = {{ bounds = [0.0, 1.0],    start = 0.5,   transform = "identity", prior = {{ uniform = {{}} }} }}
gamma   = {{ bounds = [0.1, 0.5],    start = 0.2,   transform = "identity", prior = {{ uniform = {{}} }} }}
phi     = {{ bounds = [-135.0, -45.0], start = -90.0, transform = "identity", prior = {{ uniform = {{}} }} }}
eta0    = {{ bounds = [1.0, 10.0],   start = 5.0,   transform = "identity", prior = {{ uniform = {{}} }} }}
i0      = {{ bounds = [{i0_lo:.6e}, {i0_hi:.6e}], start = {i0_start:.6e}, transform = "log", prior = {{ uniform = {{}} }}, ivp = true }}
sigma_i = {{ bounds = [0.5, 100000.0], start = {sig_start:.1f}, transform = "log", prior = {{ uniform = {{}} }} }}
"""

# lam bounds differ between the paper's supplement (Table S2: [0, 0.03])
# and its code (r_lamb = (0, 0.2)). "sirx" uses the code's range; the
# "sirx_s2" variant uses the supplement's, which is what reproduces the
# paper's published parameter estimates and its wave-2 behaviour rebound.
SIRX_ESTIMATES = """\
eps     = {{ bounds = [0.1, 0.8],    start = 0.4,   transform = "identity", prior = {{ uniform = {{}} }} }}
kappa   = {{ bounds = [100.0, 5000.0], start = 1000.0, transform = "log", prior = {{ uniform = {{}} }} }}
lam     = {{ bounds = [0.0, {lam_hi}],   start = 0.01,  transform = "identity", prior = {{ uniform = {{}} }} }}
c       = {{ bounds = [0.0, 0.01],   start = 0.001, transform = "identity", prior = {{ uniform = {{}} }} }}
x0      = {{ bounds = [1e-4, {x0_hi}], start = {x0_start:.4f}, transform = "log", prior = {{ uniform = {{}} }}, ivp = true }}
"""

TEMPLATE = """\
# {country} / {model} — generated by gen_fits.py, do not edit by hand
output_dir = "../results"

[model]
camdl = "../{model}_covid.camdl"

[data.observations]
# training window only: the paper's first-wave cutoff is day {cutoff}
{observations}

[estimate]
{estimates}

[fixed]
pop = {pop}
{fixed_extra}
[stages.scout]
algorithm = "nl-sbplx"
backend   = "ode"
chains    = {scout_chains}
init      = "lhs"
max_evals = 3000

[stages.posterior]
algorithm  = "mh"
backend    = "ode"
chains     = 4
iterations = {mh_iters}
burn_in    = {mh_burn}
init_mle   = "scout"

[config]
dt = 0.25
"""


def main() -> None:
    FIT_DIR.mkdir(exist_ok=True)
    for name, _, pop, cutoff, x0_hi, _ in COUNTRIES:
        i0_lo, i0_hi = 1.0 / pop, 2000.0 / pop
        shared = SHARED_ESTIMATES.format(
            i0_lo=i0_lo, i0_hi=i0_hi, i0_start=(i0_lo * i0_hi) ** 0.5,
            sig_start=max(2.0, pop * 2e-5),
        )
        for model in ("sir", "sirx", "sirx_s2"):
            obs = [f'cases = "../data/{name}_cases_train.tsv"']
            estimates = shared
            if model.startswith("sirx"):
                obs.append(f'osi = "../data/{name}_osi_train.tsv"')
                estimates += SIRX_ESTIMATES.format(
                    x0_hi=x0_hi, x0_start=x0_hi / 2.0,
                    lam_hi=0.2 if model == "sirx" else 0.03,
                )
            # sigma_x is fixed, not fitted: with a free scale the ML solution
            # inflates it to wash out the OSI stream entirely (the paper's
            # Belarus/Finland failure mode, but for every country). 300
            # permille is the paper's own typical accepted behaviour RMS
            # (median Error_X^0.5 = 0.29-0.50 across its final particles).
            fixed_extra = "sigma_x = 300.0\n" if model.startswith("sirx") else ""
            text = TEMPLATE.format(
                country=name, model="sirx" if model == "sirx_s2" else model,
                cutoff=cutoff, pop=pop,
                observations="\n".join(obs), estimates=estimates,
                fixed_extra=fixed_extra,
                scout_chains=12 if model == "sir" else 24,
                mh_iters=80000, mh_burn=30000,
            )
            (FIT_DIR / f"{name}_{model}.toml").write_text(text)
    print(f"wrote {len(list(FIT_DIR.glob('*.toml')))} fit configs to {FIT_DIR}")


if __name__ == "__main__":
    main()
