"""A Meteor-style steganographic channel over a language model.

The sender turns a secret payload into stegotext that, to anyone without the
key, is distributed like ordinary samples from the model. The receiver replays
the model on the observed tokens and recovers the payload.

Mechanism (the core of Kaptchuk et al.'s Meteor, CCS 2021):

1. ``cipher = plaintext XOR keystream`` -- a pseudorandom-looking bit stream,
   where ``plaintext`` is a length header followed by the payload.
2. The sender *arithmetic-decodes* the cipher into tokens using the model's
   next-token distributions. Decoding a (pseudo)random stream yields tokens
   distributed exactly like the model, so an observer sees ordinary text.
3. The receiver *arithmetic-encodes* the tokens back into the cipher and XORs
   the keystream away.

Because arithmetic coding carries undetermined low-order state forward in its
range register, the payload rate reaches the entropy of the text -- high-entropy
stretches carry many bits per token, near-deterministic stretches carry almost
none, and the channel never stalls.

A model is any object with ``dist(context) -> np.ndarray`` giving the next-token
distribution over a vocabulary of size at most ``2**FREQ_BITS``. Encoder and
decoder call it identically, so it must be deterministic in its context.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np

from . import arithcoder as ac
from .prf import bits_to_bytes, bytes_to_bits, keystream
from .sampler import entropy_bits

HEADER_BITS = 16  # payload length in bytes, big-endian


def _bits_to_int(bits) -> int:
    value = 0
    for b in bits:
        value = (value << 1) | int(b)
    return value


@dataclass
class EmbedResult:
    tokens: list[int]
    committed_per_token: list[int] = field(default_factory=list)
    entropy_per_token: list[float] = field(default_factory=list)


def _entropies(model, tokens: list[int]) -> list[float]:
    ctx: list[int] = []
    hs = []
    for t in tokens:
        hs.append(entropy_bits(model.dist(ctx)))
        ctx.append(t)
    return hs


FLUSH_MARGIN = 64  # extra determined bits to push the payload out of the register


def _pad_bits(cipher: np.ndarray, n: int) -> np.ndarray:
    """Deterministic pseudorandom padding, keyed only by the cipher itself."""
    import hashlib

    out, seed = [], bits_to_bytes(cipher) + b"pad"
    while len(out) < n:
        seed = hashlib.sha256(seed).digest()
        out.extend(np.unpackbits(np.frombuffer(seed, dtype=np.uint8)).tolist())
    return np.array(out[:n], dtype=np.uint8)


def embed_bits(model, cipher, max_tokens: int = 200_000) -> EmbedResult:
    """Emit tokens carrying ``cipher`` bits; measure bits committed per token."""
    cipher = np.asarray(cipher, dtype=np.uint8)
    nbits = len(cipher)

    # Append pseudorandom cover bits so the last payload bits become "determined"
    # (emitted) rather than trapped in the coder's range register. Cover-driven
    # tokens are never recovered -- the receiver reads only the first nbits.
    work = np.concatenate([cipher, _pad_bits(cipher, FLUSH_MARGIN + 128)])
    tokens, _ = ac.decode(model, work, min_consumed=nbits + FLUSH_MARGIN,
                          max_tokens=max_tokens)

    bits, deltas = ac.encode(model, tokens)
    if len(bits) < nbits:
        raise RuntimeError("could not commit all payload bits (text too short)")

    return EmbedResult(tokens=tokens, committed_per_token=deltas,
                       entropy_per_token=_entropies(model, tokens))


def extract_bits(model, tokens: list[int], nbits: int) -> np.ndarray:
    """Recover the first ``nbits`` cipher bits from stegotext ``tokens``."""
    bits, _ = ac.encode(model, tokens)
    return np.array(bits[:nbits], dtype=np.uint8)


def encode_message(model, key: bytes, payload: bytes, max_tokens: int = 200_000) -> list[int]:
    """Hide ``payload`` bytes in stegotext generated by ``model``."""
    if len(payload) >= (1 << HEADER_BITS):
        raise ValueError("payload too long for 16-bit header")
    header = np.array([(len(payload) >> (HEADER_BITS - 1 - j)) & 1
                       for j in range(HEADER_BITS)], dtype=np.uint8)
    plain = np.concatenate([header, bytes_to_bits(payload)])
    cipher = np.bitwise_xor(plain, keystream(key, len(plain)))
    return embed_bits(model, cipher, max_tokens=max_tokens).tokens


def decode_message(model, key: bytes, tokens: list[int]) -> bytes:
    """Recover the payload hidden in ``tokens``. Reads the length header first."""
    bits, _ = ac.encode(model, tokens)
    bits = np.array(bits, dtype=np.uint8)

    head = np.bitwise_xor(bits[:HEADER_BITS], keystream(key, HEADER_BITS))
    n_payload = _bits_to_int(head)

    # A wrong key yields a garbage header (and length); decode whatever bits are
    # available rather than crashing, so callers see garbage, not an exception.
    total = min(HEADER_BITS + n_payload * 8, len(bits))
    total -= (total - HEADER_BITS) % 8  # whole bytes only
    plain = np.bitwise_xor(bits[:total], keystream(key, total))
    return bits_to_bytes(plain[HEADER_BITS:])
