"""A distortion-free watermark in the Christ-Gunn-Zamir / Aaronson family.

This is the "one hidden bit" cousin of the steganographic channel: instead of
carrying an arbitrary payload, it embeds a single fact -- "this text was
generated by us" -- that a key holder can detect but nobody else can even notice.

Construction (the exponential-minimum / Gumbel trick, which Aaronson proposed
for GPT and which the CGZ analysis places in the undetectable-watermark family):

- At each position, derive a keyed Uniform(0, 1) score ``r_v`` for every candidate
  token ``v`` from ``PRF(key, context)``.
- Emit ``argmax_v r_v ** (1 / p_v)``. This samples *exactly* from ``p`` (so the
  output distribution is untouched -- the watermark is distortion-free), yet the
  emitted token tends to have an unusually large ``r``.

Detection replays the scores and sums ``-ln(1 - r)`` over the emitted tokens.
Under the null (text we did not generate) each term is Exponential(1), so the
sum is Gamma(T, 1); watermarked text pushes the sum into the tail. Detection
power grows with the entropy of the text: a near-deterministic token is forced
regardless of ``r`` and leaks no signal, while a high-entropy choice is driven by
``r`` and leaks a lot.
"""

from __future__ import annotations

import numpy as np
from scipy import stats

from .prf import uniforms


def _context_bytes(context: list[int]) -> bytes:
    # A small context window keeps scores reproducible and position-dependent.
    window = context[-5:]
    return b"|".join(str(t).encode() for t in window) + b"#" + str(len(context)).encode()


def generate(model, key: bytes, n_tokens: int) -> list[int]:
    """Generate ``n_tokens`` watermarked tokens from ``model``."""
    tokens: list[int] = []
    for _ in range(n_tokens):
        p = np.asarray(model.dist(tokens), dtype=np.float64)
        r = uniforms(key, _context_bytes(tokens), len(p))
        # argmax r ** (1/p) == argmax (ln r) / p ; guard zero-probability tokens.
        with np.errstate(divide="ignore"):
            score = np.where(p > 0, np.log(r) / p, -np.inf)
        tokens.append(int(np.argmax(score)))
    return tokens


def detect(model, key: bytes, tokens: list[int]) -> dict:
    """Return the watermark test statistic, z-score, and p-value for ``tokens``."""
    context: list[int] = []
    stat = 0.0
    for tok in tokens:
        p = np.asarray(model.dist(context), dtype=np.float64)
        r = uniforms(key, _context_bytes(context), len(p))
        r_tok = min(max(float(r[tok]), 1e-12), 1 - 1e-12)
        stat += -np.log(1.0 - r_tok)
        context.append(tok)

    n = len(tokens)
    # Under H0, stat ~ Gamma(n, 1): mean n, variance n.
    p_value = float(stats.gamma.sf(stat, a=n, scale=1.0)) if n > 0 else 1.0
    z = (stat - n) / np.sqrt(n) if n > 0 else 0.0
    return {"stat": float(stat), "n": n, "z": float(z), "p_value": p_value}
