"""Programmatically assemble replicate_ews.ipynb from cell sources.

Keeping the notebook's prose and code here (rather than editing raw JSON) makes
the narrative easy to revise. Run ``python build_notebook.py`` to (re)generate
the notebook, then execute it with nbconvert.
"""

import nbformat as nbf

nb = nbf.v4.new_notebook()
cells = []


def md(text):
    cells.append(nbf.v4.new_markdown_cell(text.strip("\n")))


def code(text):
    cells.append(nbf.v4.new_code_cell(text.strip("\n")))


# ---------------------------------------------------------------- title / TL;DR
md(r"""
# Can we see an epidemic coming — and does social media help?

*A clean-room replication of* **Olajide, Lutscher & Smith (2026),**
*"Early-warning signals for infectious diseases with a social-media compartment,"*
PLOS ONE, [10.1371/journal.pone.0354091](https://doi.org/10.1371/journal.pone.0354091).

As a dynamical system approaches a tipping point it suffers **critical slowing
down**: it recovers from perturbations ever more sluggishly, so its **variance**
and **lag-1 autocorrelation** rise. Those two rising statistics are the classic
**early-warning signals (EWSs)**. This paper slowly forces a disease model past
its emergence threshold (the basic reproduction number $R_0$ crossing 1) and
asks a sharp question: do the warning signals fire in time — and can a
**social-media** signal warn us even earlier than case counts?
""")

md(r"""
## TL;DR — what this notebook reproduces

1. **The model.** A five-compartment **SWIRM** model — Susceptible, *W* (unreported
   infected), *I* (reported infected), Recovered, and *M* (social-media posts) —
   driven to emergence by a transmission rate that ramps up in time.
2. **The delay.** Emergence lags the bifurcation: $R_0$ crosses 1 at **t = 14.5 days**,
   but the outbreak only *appears* (a detectable changepoint) many weeks later.
3. **The headline result.** For reported infections, **variance beats
   autocorrelation** as a warning signal — the opposite of several earlier
   studies. For the **social-media** compartment, both signals are **no better
   than a coin flip**.

Everything numerical lives in the small `swirm/` package; each cell below calls
it and plots one idea, so the notebook stays about the science. Differences
between this replication and the published figures are collected at the end.
""")

code(r"""
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

from swirm import Params, simulate_ensemble, STATE_NAMES
from swirm.evaluate import Scenario, run_scenario, summarize
from swirm import plots

plt.rcParams.update({"figure.dpi": 110, "axes.spines.top": False, "axes.spines.right": False})

# Runtime knobs. The paper uses 300 realizations; 200 reproduces every result
# and keeps this notebook quick. Bump to 300 to match exactly.
N_REAL = 200
T_MAX = 150.0     # days; long enough to capture the delayed outbreak
DT = 0.005        # matches the paper (2900 steps to the bifurcation at 14.5 d)
CACHE = Path("results_cache.csv")

p = Params()
p
""")

# ---------------------------------------------------------------- Section 1
md(r"""
## 1. The SWIRM model

New infections appear through the mass-action term $\beta(t)\,S\,I$; a fraction
$f$ are **reported** (enter $I$) and the rest go **unreported** (enter $W$). Only
reported infections transmit. Social media is a passive *observer*: posts are
generated by, and engagement scales with, the compartments, but $M$ never feeds
back into transmission.

$$\begin{aligned}
\dot S &= \pi - \beta(t) S I - \mu S + \phi R\\
\dot W &= (1-f)\beta(t) S I - (\gamma_W+\alpha+\mu) W\\
\dot I &= f\beta(t) S I + \alpha W - (\gamma_I+\mu) I\\
\dot R &= \gamma_W W + \gamma_I I - (\mu+\phi) R\\
\dot M &= \delta\!\sum X + \epsilon M\!\sum X - \bar\mu M^2
\end{aligned}$$

Emergence is forced by a linearly rising transmission rate $\beta(t)=\beta_0+rt$.
The next-generation method gives

$$R_0(t)=\frac{\alpha(1-f)\beta S^\* + f\beta S^\*(\gamma_W+\alpha+\mu)}
{(\gamma_W+\alpha+\mu)(\gamma_I+\mu)},\qquad S^\*=\pi/\mu .$$

With the Table 1 parameters this crosses 1 at exactly **t = 14.5 days** — the check
below is the single most reassuring line in the notebook.
""")

code(r"""
bp = p.bifurcation_time()
print(f"Bifurcation (R0 = 1) at t = {bp:.3f} days   [paper: 14.5]")
print(f"R0(bifurcation) = {float(p.R0(bp)):.6f}")
assert abs(bp - 14.5) < 0.1

fig, ax = plt.subplots(figsize=(5, 3))
plots.plot_R0(p, t_max=40, ax=ax)
ax.set_title("Forcing R0 up through the critical value 1")
plt.tight_layout()
""")

# ---------------------------------------------------------------- Section 2
md(r"""
## 2. Emergence is delayed

Crossing $R_0=1$ does **not** trigger the outbreak. Because the threshold is
crossed slowly and the system lingers near the (now unstable) disease-free state
— "tracking unstable states" — the epidemic only takes off weeks later. Here is
one realization of reported infections $I$ under each of the three noise models.
The dashed line marks the bifurcation; the spike arrives far to its right.
""")

code(r"""
examples = {
    "additive (σ=1)": ("additive", 1.0),
    "multiplicative (σ=0.05)": ("multiplicative", 0.05),
    "demographic": ("demographic", 0.0),
}
fig, axes = plt.subplots(1, 3, figsize=(13, 3.2), sharex=True)
for ax, (name, (nt, sig)) in zip(axes, examples.items()):
    times, traj = simulate_ensemble(p, nt, sig, n_real=1, t_max=T_MAX, dt=DT, seed=42)
    plots.plot_realization(times, traj, p, var_index=2, ax=ax)
    ax.set_title(name, fontsize=10)
    ax.set_ylabel("reported infections I")
plt.tight_layout()
""")

# ---------------------------------------------------------------- Section 3
md(r"""
## 3. When does the epidemic *look* like it started?

We locate the observed onset with an **At-Most-One-Changepoint (AMOC)** mean-shift
test (our transparent, Monte-Carlo-calibrated stand-in for R's `cpt.mean`). A
changepoint **after** the bifurcation is a **delay**; **before** it, an
**advance**. We now run the full ensembles once and cache the per-realization
results (changepoint time, delay, and the EWS trends we use later).
""")

code(r"""
SCENARIOS = [
    Scenario("multiplicative", 0.05, "MN low"),
    Scenario("additive", 1.0, "AWN low"),
    Scenario("demographic", 0.0, "DS"),
]

if CACHE.exists():
    results = pd.read_csv(CACHE)
    print("loaded cached results")
else:
    parts = []
    for i, sc in enumerate(SCENARIOS):
        print(f"running {sc.name()} ...")
        parts.append(run_scenario(p, sc, variables=("I", "W", "M"),
                                   n_real=N_REAL, t_max=T_MAX, dt=DT, seed=100 + i))
    results = pd.concat(parts, ignore_index=True)
    results.to_csv(CACHE, index=False)
print(results.shape)
""")

code(r"""
# Delay vs advance, by scenario and compartment (cf. the paper's Figs 3–5 text).
tab = (results.groupby(["scenario", "variable"])["is_delay"].mean()
       .unstack().mul(100).round(0))
print("Percent of realizations showing a DELAY (changepoint after bifurcation):")
tab
""")

code(r"""
# Density of changepoint locations for reported infections I (cf. Fig 3/4/5).
fig, ax = plt.subplots(figsize=(6.5, 3.5))
for sc in SCENARIOS:
    d = results[(results.scenario == sc.name()) & (results.variable == "I")]["cp_time"].dropna()
    ax.hist(d, bins=40, histtype="step", density=True, lw=1.6, label=sc.name())
ax.axvline(p.bifurcation_time(), color="k", ls="--", lw=1, label="bifurcation")
ax.set_xlabel("changepoint time (days)"); ax.set_ylabel("density")
ax.set_title("When the outbreak becomes detectable in I")
ax.legend(frameon=False, fontsize=8); plt.tight_layout()
""")

# ---------------------------------------------------------------- Section 4
md(r"""
## 4. Reading the warning signals

For each realization we take two equal-length windows — one running up to the
**bifurcation** (no transition ahead of it yet) and one running up to the
**changepoint** (a real transition ahead) — Gaussian-detrend them, and compute
the trend (Kendall's $\tau$) of rolling **variance** and **lag-1
autocorrelation**. A good warning signal is **negative before the bifurcation**
(nothing coming) and **positive before the changepoint** (something coming).

The raincloud below (reported infections, multiplicative noise) is the paper's
Fig 6. Variance leading up to the changepoint piles up near $\tau=+1$; the
autocorrelation is far less decisive.
""")

code(r"""
d = results[(results.scenario == "MN low") & (results.variable == "I")]
groups = {
    "variance\n→ bifurcation": d["tau_var_bp"],
    "variance\n→ changepoint": d["tau_var_cp"],
    "autocorr\n→ bifurcation": d["tau_ac_bp"],
    "autocorr\n→ changepoint": d["tau_ac_cp"],
}
fig, ax = plt.subplots(figsize=(7.5, 4))
plots.raincloud(groups, ax=ax, title="Kendall-τ of EWSs for I (multiplicative noise, low)")
plt.tight_layout()
""")

# ---------------------------------------------------------------- Section 5
md(r"""
## 5. Do the signals actually work?

We score each signal with an **ROC curve**: treating changepoint-windows as the
positives and bifurcation-windows as the negatives, how well does the $\tau$ of
variance (or autocorrelation) separate them? The area under the curve (AUC) is
1 for a perfect signal and 0.5 for a coin flip.
""")

code(r"""
fig, axes = plt.subplots(1, 3, figsize=(13, 3.6))
for ax, var in zip(axes, ("I", "W", "M")):
    d = results[(results.scenario == "MN low") & (results.variable == var)]
    plots.plot_roc(d, var, ax=ax)
axes[0].set_ylabel("true positive rate")
fig.suptitle("EWS performance under multiplicative noise (low): variance vs autocorrelation", y=1.03)
plt.tight_layout()
""")

md(r"""
The pattern is the paper's central result. For **reported infections (I)** and
**unreported infections (W)** variance carries a real signal and beats
autocorrelation; for the **social-media compartment (M)** both curves hug the
diagonal — **no predictive power**. The summary table below is our version of
the paper's Table 2 (percent positive $\tau$) and Figs 7–10 (AUC).
""")

code(r"""
summary = summarize(results)
cols = ["scenario", "variable", "n_delay",
        "pct_pos_var_bp", "pct_pos_var_cp", "pct_pos_ac_bp", "pct_pos_ac_cp",
        "auc_variance", "auc_autocorr"]
summary[cols].round(2).sort_values(["scenario", "variable"]).reset_index(drop=True)
""")

# ---------------------------------------------------------------- Section 6
md(r"""
## 6. What it means, and how it fits the literature

- **Variance > autocorrelation.** For reported infections, variance is the
  reliable warning; autocorrelation is near-random. This *contradicts*
  O'Regan & Burton and Chakraborty et al. (who favored autocorrelation) and
  *agrees* with the studies the authors cite on the other side. The likely
  reconciler is model dimensionality and noise structure — a five-dimensional,
  time-forced system behaves differently from the one-dimensional models where
  autocorrelation won.
- **Social media does not warn.** Even though posts are generated mechanistically
  from the true epidemic, classical EWSs read them at chance. The signal is
  drowned by the media compartment's own fast, noisy dynamics — a caution against
  assuming online chatter inherits the epidemic's critical slowing down.
- **Delays are real but survivable.** Emergence lags the bifurcation, yet EWSs
  computed on the *approach to the changepoint* still fire — extending
  O'Regan & Drake's more pessimistic reading.

**Caveat:** this is a simulation study. The authors propose validating on real
outbreaks by reconstructing $R_t$ with EpiEstim and running the same pipeline on
incidence — and applying the media arm directly to tweet volumes.

### Where this replication differs from the paper

See `PLAN.md` and the repo `README.md` for the running list. The big ones:

1. **Noise intensities** for additive/multiplicative low/medium/high are not in
   the machine-readable text (only figure captions), so we chose values. This
   shifts AUC *magnitudes* for additive noise but not the qualitative story.
2. **Demographic stochasticity** produces mostly *delays* here, whereas the paper
   reports ~70% *advances*. Our AMOC penalty is calibrated to avoid the spurious
   early changepoints that the paper notes high demographic noise can create — the
   likely source of most of their "advances."
3. **Changepoint / detrending tools** are transparent NumPy reimplementations of
   R's `cpt.mean` (AMOC) and `earlywarnings` (Gaussian detrend + rolling window),
   not the exact R packages, so small numeric differences are expected.
""")

nb["cells"] = cells
nb["metadata"] = {
    "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
    "language_info": {"name": "python"},
}
nbf.write(nb, "replicate_ews.ipynb")
print("wrote replicate_ews.ipynb with", len(cells), "cells")
